# Base configuration with default values. Override any parameter as needed.
# See config.go for all available parameters.
participants:
  - "001"
  - "002"
  - "003"
  - "004"
  - "005"
  - "006"
  - "007"
  - "008"
